name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: Chesterkxng
          outputs: dist/snake.svg

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@users.noreply.github.com"
          git add -f dist/snake.svg
          git commit -m "Generate snake.svg"
          git push
